### ISSUE TITLE
U-SQL Script Job Scheduling???

### ISSUE THREAD

**Issue by aceptra** [Azure/usql#77]
We're looking to potentially migrate a series of SQL Server based SQL jobs from our "analytics engine" to Azure Data Lake. Typically we do the scheduling through an SQL Server Integration Services (SSIS) directed graph, which allows for asynchronous operation. The end result is a few tables/files as output.

I'm not seeing any SSIS extensions other than the "Azure Data Lake Store" source and destination DFTs. In contrast HDInsight has a few Pig, Hive execution SSIS tasks and REST APIs.

# Question
What is the typical goto method for executing a series U-SQL jobs, either in series or asynchronously? I see sample projects show order system with a number prepended to individual U-SQL script files. 

Thank you,

Jon

**Comment by serri588** [comment]
If you are running on a regular schedule, Data Factory can handle this just fine: https://docs.microsoft.com/en-us/azure/data-factory/data-factory-usql-activity

We're moving from that to a console app that can be triggered from SSIS that basically does the same thing as the Data Factory activity since this client is more comfortable with SSIS. A few tweaks to the .NET tutorial was all we needed to create the app: https://docs.microsoft.com/en-us/azure/data-lake-analytics/data-lake-analytics-get-started-net-sdk. A custom script task would work as well.

That being said, I would like to see SSIS be able to run ADLA jobs without custom code.

**Comment by aceptra** [comment]
yes someone else finally pointed me to the SDK, and by that example custom SSIS scripts can do C#. Of course native SSIS tasks for would be better. Seems the U-SQL tooling isn't quite there yet.

**Comment by MikeRys** [comment]
Please contact me directly and I can forward your request regarding SSIS support and vote up the following items (depending on what you need):

https://feedback.azure.com/forums/327234-data-lake/suggestions/17111080-provide-ssis-adla-download-upload-task
https://feedback.azure.com/forums/327234-data-lake/suggestions/17111116-make-adla-files-and-tables-be-sources-in-ssis-data
https://feedback.azure.com/forums/327234-data-lake/suggestions/13138122-call-usql-code-inside-ssis-and-create-usql-framewo
