### ISSUE TITLE
Parallel Avro Extractor

### ISSUE THREAD

**Issue by mayoatbm** [Azure/usql#96]
How do we make the current Avro extractor work in parallel i.e  with AtomicFileProcessing=false. This would improve performance a lot by allowing the extraction step to be parallelized.

Is the main issue that the header block would be included in one of the splits (assuming we use the input.Split method with the sync marker as the delimiter)?

**Comment by rdefreitas** [comment]
I'm trying to figure out the same problem

**Comment by MikeRys** [comment]
You are correct that you cannot execute it in parallel since the header information would be lost on the other vertices. You have to upvote the request for a built-in, parallelizable AVRO extractor at http://aka.ms/adlfeedback.

**Comment by flomader** [comment]
Unfortunately that cannot be solved in the Avro Extractor itself. Azure Data Lake Store needs to be aware of the Avro file format and split Avro files correctly over extents.
Though, there would only a performance improvement if you process larger files (~1GB+) because smaller files won't get processed in multiple vertices anyway (at least that's what I have seen when I tested it).

**Comment by mayoatbm** [comment]
Thanks for the clarification, gents.  

@rdefreitas We ended up moving away from avro as a storage format in Data Lake. We moved to row delimited json instead and that has been better so far. Are you working with event hub capture by any chance?
